In [74]:
# Importing the dataset
!pip install -U -q PyDrive
  
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
  
  
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [75]:
link = 'https://drive.google.com/file/d/1SYM-eE5N3YHXfEmd-lgGuVv-Xe1-E9N-/view?usp=sharing'
  
import pandas as pd

In [76]:
# to get the id part of the file
id = link.split("/")[-2]
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('energydata_complete.csv')  
  
df = pd.read_csv('energydata_complete.csv')
print(df)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [77]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
#viewing all rows and columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
# display first 5 rows of dataset
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,55.20,7.026667,84.256667,17.200000,41.626667,18.2,48.900000,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,55.20,6.833333,84.063333,17.200000,41.560000,18.2,48.863333,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,55.09,6.560000,83.156667,17.200000,41.433333,18.2,48.730000,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,55.09,6.433333,83.423333,17.133333,41.290000,18.1,48.590000,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,55.09,6.366667,84.893333,17.200000,41.230000,18.1,48.590000,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [67]:

df_new=df.drop(df.columns.difference(['T2','T6']), 1, inplace=True)

In [69]:
# checking null-values
df.isnull().sum()

T2    0
T6    0
dtype: int64

In [70]:
#More info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   T2      19735 non-null  float64
 1   T6      19735 non-null  float64
dtypes: float64(2)
memory usage: 308.5 KB

In [71]:
# stats of all columns
df.describe()

                 T2            T6
count  19735.000000  19735.000000
mean      20.341219      7.910939
std        2.192974      6.090347
min       16.100000     -6.065000
25%       18.790000      3.626667
50%       20.000000      7.300000
75%       21.500000     11.256000
max       29.856667     28.290000

In [73]:
# separating T6(target variable)
df_features= df.drop(columns=['T6'])
T6_target = df_new['T6']
T6_target.head()

TypeError: ignored

In [54]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(T2_predictor,T6_target, test_size = 0.3, random_state = 42)

In [61]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
df_new_normalised = pd.DataFrame(scaler.fit_transform(df_new), columns=df_new.columns)
#X_train = sc_X.fit_transform(X_train)
#X_test = sc_X.transform(X_test)
#sc_y = StandardScaler()
#y_train = sc_y.fit_transform(y_train)

In [49]:
#splitting normalized dataset into 70-30 train-test set with a random state of 42(for reproducibility).
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(T2_predictor, T6_target, test_size=0.3, random_state=42)

In [44]:
# Import Linear Regression Model
from sklearn.linear_model import LinearRegression
model_linear = LinearRegression()
#fit the model to the training dataset
model_linear.fit(x_train, y_train)
#obtain predictions
predicted_values = model_linear.predict(x_test)

ValueError: ignored